export const API_Constant = {
  ACTIVATIONS: {
    CREATE_ACTIVATION: 'Activations/create-activation',
    GET_ALL_ACTIVATIONS: 'Activations/get-all-activations',
    GET_ACTIVATION_BY_ID: 'Activations/get-activation-by-id/',
    UPDATE_ACTIVATION: 'Activations/update-activation/',
    DELETE_ACTIVATIONS: 'Activations/delete-activation/',
    FILTER_ACTIVATIONS: 'Activations/filter',
  },
  BRANCH: {
    CREATE_BRANCH: 'BranchMaster/create-branch',
    GET_ALL_BRANCHES: 'BranchMaster/get-all-branches',
    GET_BRANCH_BY_ID: 'BranchMaster/get-branch-by-id/',
    UPDATE_BRANCH: 'BranchMaster/update-branch',
    DELETE_BRANCH: 'BranchMaster/delete-branch/',
  },
  COURSE: {
    CREATE_COURSE: 'Course/createCourse',
    GET_ALL_COURSES: 'Course/getAllCourses',
    GET_COURSE_BY_ID: 'Course/getCourseById/',
    UPDATE_COURSE: 'Course/updateCourse',
    DELETE_COURSE: 'Course/deleteCourse/',
    GET_COURSE_BY_INSTITUTE_ID: 'Course/getCoursesByInstitute/',
  },
  ENROLLMENT: {
    CREATE_ENROLLMENT: 'Enrollments/createStudentEnrollment',
    GET_ALL_ENROLLMENTS_BY_INSTITUTE_ID: 'Enrollments/getAllEnrollments/',
    GET_ENROLLMENT_BY_ID: 'Enrollments/getEnrollmentById/',
    UPDATE_ENROLLMENT: 'Enrollments/updateEnrollment/',
    DELETE_ENROllment: 'Enrollments/deleteEnrollment/',
    GET_ALL_PENDING_ENROLLMENTS_BY_INSTITUTE_ID: 'Enrollments/getAllPendingEnrollments/',
  },
  INSTITUTE_Master: {
    CREATE_INSTITUTE: 'InstituteMaster/create-institute',
    GET_ALL_INSTITUTES: 'InstituteMaster/get-all-institutes',
    GET_INSTITUE_BY_ID: 'InstituteMaster/get-institute-by-id/',
    UPDATA_INSTITUTE: 'InstituteMaster/update-institute/',
    DELETE_INSTITUTE: 'InstituteMaster/delete-institute/',
  },
  MASTER: {
    GET_ALL_MASTERS: 'Master/get-all-masters',
    CREATE_MASTER: 'Master/create-master',
    UPDATE_MASTER: 'Master/update-master/',
    DELETE_MASTER: 'Master/delete-master/',
  },

  PACKAGE_MASTER: {
    CREATE_PACKAGE: 'PackageMaster/create-package',
    GET_ALL_PACKAGES: 'PackageMaster/get-all-packages',
    PACKAGE_BY_ID: 'PackageMaster/get-package-by-id/',
    UPDATE_PACKAGE: 'PackageMaster/update-package/',
    DELETE_PACKAGE: 'PackageMaster/delete-package/',
  },
  PAYMENT: {
    CREATE_PAYMENT: 'Payments/createPayment',
    GET_ALL_PAYMENTS_BY_INSTITUTE_ID: 'Payments/getAllPaymentsByInstituteId/',
    GET_PAYMENT_BY_ID: 'Payments/getPaymentById/',
    UPDATE_PAYMENT: 'Payments/updatePayment/',
    DELETE_PAYMENT: 'Payments/deletePayment/',
    FILTER_PAYMENTS: 'Payments/filterPayments',
  },
  STUDENT: {
    CREATE_STUDENT: 'Student',
    GET_STUDENTS_BY_INSTITUTE_ID: 'Student/institute/',
    GET_STUDENT_BY_ID: 'Student/',
    UPDATE_STUDENT: 'Student/',
    DELETE_STUDENT: 'Student/',
  },
  USER: {
    CREATE_USER: 'User/login',
    GET_ALL_USERS: 'User/get-all-users',
    GET_USER_BY_ID: 'User/get-user-by-id/',
    UPDATE_USER: 'User/update-user/',
    DELETE_USER: 'User/delete-user/',
  },
};
